// this file was generated by https://github.com/Java-Jonas/decltostring

package statefactory

const input_person_type string = `type person struct {
	name		name
	children	[]child
	age		int
}`

const input_name_type string = `type name struct {
	first	string
	last	string
}`

const input_child_type string = `type child struct{ name name }`
