// this file was generated by https://github.com/Java-Jonas/decltostring

package statefactory

const AddPlayer_Zone_func string = `func (_e Zone) AddPlayer(sm *StateMachine) Player {
	e := sm.GetZone(_e.zone.ID)
	if e.zone.OperationKind == OperationKindDelete {
		return Player{}
	}
	player := sm.createPlayer(true)
	e.zone.Players = append(e.zone.Players, player.player.ID)
	e.zone.OperationKind = OperationKindUpdate
	sm.Patch.Zone[e.zone.ID] = e.zone
	return player
}`

const AddZoneItem_Zone_func string = `func (_e Zone) AddZoneItem(sm *StateMachine) ZoneItem {
	e := sm.GetZone(_e.zone.ID)
	if e.zone.OperationKind == OperationKindDelete {
		return ZoneItem{}
	}
	zoneItem := sm.createZoneItem(true)
	e.zone.Items = append(e.zone.Items, zoneItem.zoneItem.ID)
	e.zone.OperationKind = OperationKindUpdate
	sm.Patch.Zone[e.zone.ID] = e.zone
	return zoneItem
}`

const AddTags_Zone_func string = `func (_e Zone) AddTags(sm *StateMachine, tags ...string) {
	e := sm.GetZone(_e.zone.ID)
	if e.zone.OperationKind == OperationKindDelete {
		return
	}
	e.zone.Tags = append(e.zone.Tags, tags...)
	e.zone.OperationKind = OperationKindUpdate
	sm.Patch.Zone[e.zone.ID] = e.zone
}`

const AddItem_Player_func string = `func (_e Player) AddItem(sm *StateMachine) Item {
	e := sm.GetPlayer(_e.player.ID)
	if e.player.OperationKind == OperationKindDelete {
		return Item{}
	}
	item := sm.createItem(true)
	e.player.Items = append(e.player.Items, item.item.ID)
	e.player.OperationKind = OperationKindUpdate
	sm.Patch.Player[e.player.ID] = e.player
	return item
}`

const assembleGearScore_StateMachine_func string = `func (sm *StateMachine) assembleGearScore(gearScoreID GearScoreID) (_gearScore, bool) {
	gearScore, hasUpdated := sm.Patch.GearScore[gearScoreID]
	if !hasUpdated {
		return _gearScore{}, false
	}
	var treeGearScore _gearScore
	treeGearScore.ID = gearScore.ID
	treeGearScore.OperationKind = gearScore.OperationKind
	treeGearScore.Level = gearScore.Level
	treeGearScore.Score = gearScore.Score
	return treeGearScore, true
}`

const assemblePosition_StateMachine_func string = `func (sm *StateMachine) assemblePosition(positionID PositionID) (_position, bool) {
	position, hasUpdated := sm.Patch.Position[positionID]
	if !hasUpdated {
		return _position{}, false
	}
	var treePosition _position
	treePosition.ID = position.ID
	treePosition.OperationKind = position.OperationKind
	treePosition.X = position.X
	treePosition.Y = position.Y
	return treePosition, true
}`

const assembleItem_StateMachine_func string = `func (sm *StateMachine) assembleItem(itemID ItemID) (_item, bool) {
	item, hasUpdated := sm.Patch.Item[itemID]
	if !hasUpdated {
		item = sm.State.Item[itemID]
	}
	var treeItem _item
	if treeGearScore, gearScoreHasUpdated := sm.assembleGearScore(item.GearScore); gearScoreHasUpdated {
		hasUpdated = true
		treeItem.GearScore = &treeGearScore
	}
	treeItem.ID = item.ID
	treeItem.OperationKind = item.OperationKind
	return treeItem, hasUpdated
}`

const assembleZoneItem_StateMachine_func string = `func (sm *StateMachine) assembleZoneItem(zoneItemID ZoneItemID) (_zoneItem, bool) {
	zoneItem, hasUpdated := sm.Patch.ZoneItem[zoneItemID]
	if !hasUpdated {
		zoneItem = sm.State.ZoneItem[zoneItemID]
	}
	var treeZoneItem _zoneItem
	if treeItem, itemHasUpdated := sm.assembleItem(zoneItem.Item); itemHasUpdated {
		hasUpdated = true
		treeZoneItem.Item = &treeItem
	}
	if treePosition, positionHasUpdated := sm.assemblePosition(zoneItem.Position); positionHasUpdated {
		hasUpdated = true
		treeZoneItem.Position = &treePosition
	}
	treeZoneItem.ID = zoneItem.ID
	treeZoneItem.OperationKind = zoneItem.OperationKind
	return treeZoneItem, hasUpdated
}`

const assemblePlayer_StateMachine_func string = `func (sm *StateMachine) assemblePlayer(playerID PlayerID) (_player, bool) {
	player, hasUpdated := sm.Patch.Player[playerID]
	if !hasUpdated {
		player = sm.State.Player[playerID]
	}
	var treePlayer _player
	if treeGearScore, gearScoreHasUpdated := sm.assembleGearScore(player.GearScore); gearScoreHasUpdated {
		hasUpdated = true
		treePlayer.GearScore = &treeGearScore
	}
	for _, itemID := range deduplicateItemIDs(sm.State.Player[player.ID].Items, sm.Patch.Player[player.ID].Items) {
		if treeItem, itemHasUpdated := sm.assembleItem(itemID); itemHasUpdated {
			hasUpdated = true
			treePlayer.Items = append(treePlayer.Items, treeItem)
		}
	}
	if treePosition, positionHasUpdated := sm.assemblePosition(player.Position); positionHasUpdated {
		hasUpdated = true
		treePlayer.Position = &treePosition
	}
	treePlayer.ID = player.ID
	treePlayer.OperationKind = player.OperationKind
	return treePlayer, hasUpdated
}`

const assembleZone_StateMachine_func string = `func (sm *StateMachine) assembleZone(zoneID ZoneID) (_zone, bool) {
	zone, hasUpdated := sm.Patch.Zone[zoneID]
	if !hasUpdated {
		zone = sm.State.Zone[zoneID]
	}
	var treeZone _zone
	for _, zoneItemID := range deduplicateZoneItemIDs(sm.State.Zone[zone.ID].Items, sm.Patch.Zone[zone.ID].Items) {
		if treeZoneItem, zoneItemHasUpdated := sm.assembleZoneItem(zoneItemID); zoneItemHasUpdated {
			hasUpdated = true
			treeZone.Items = append(treeZone.Items, treeZoneItem)
		}
	}
	for _, playerID := range deduplicatePlayerIDs(sm.State.Zone[zone.ID].Players, sm.Patch.Zone[zone.ID].Players) {
		if treePlayer, playerHasUpdated := sm.assemblePlayer(playerID); playerHasUpdated {
			hasUpdated = true
			treeZone.Players = append(treeZone.Players, treePlayer)
		}
	}
	treeZone.ID = zone.ID
	treeZone.OperationKind = zone.OperationKind
	treeZone.Tags = zone.Tags
	return treeZone, hasUpdated
}`

const assembleTree_StateMachine_func string = `func (sm *StateMachine) assembleTree() Tree {
	tree := newTree()
	for _, gearScore := range sm.Patch.GearScore {
		if !gearScore.HasParent {
			treeGearScore, hasUpdated := sm.assembleGearScore(gearScore.ID)
			if hasUpdated {
				tree.GearScore[gearScore.ID] = treeGearScore
			}
		}
	}
	for _, item := range sm.Patch.Item {
		if !item.HasParent {
			treeItem, hasUpdated := sm.assembleItem(item.ID)
			if hasUpdated {
				tree.Item[item.ID] = treeItem
			}
		}
	}
	for _, player := range sm.Patch.Player {
		if !player.HasParent {
			treePlayer, hasUpdated := sm.assemblePlayer(player.ID)
			if hasUpdated {
				tree.Player[player.ID] = treePlayer
			}
		}
	}
	for _, position := range sm.Patch.Position {
		if !position.HasParent {
			treePosition, hasUpdated := sm.assemblePosition(position.ID)
			if hasUpdated {
				tree.Position[position.ID] = treePosition
			}
		}
	}
	for _, zone := range sm.Patch.Zone {
		treeZone, hasUpdated := sm.assembleZone(zone.ID)
		if hasUpdated {
			tree.Zone[zone.ID] = treeZone
		}
	}
	for _, zoneItem := range sm.Patch.ZoneItem {
		if !zoneItem.HasParent {
			treeZoneItem, hasUpdated := sm.assembleZoneItem(zoneItem.ID)
			if hasUpdated {
				tree.ZoneItem[zoneItem.ID] = treeZoneItem
			}
		}
	}
	for _, gearScore := range sm.State.GearScore {
		if !gearScore.HasParent {
			if _, ok := tree.GearScore[gearScore.ID]; !ok {
				treeGearScore, hasUpdated := sm.assembleGearScore(gearScore.ID)
				if hasUpdated {
					tree.GearScore[gearScore.ID] = treeGearScore
				}
			}
		}
	}
	for _, item := range sm.State.Item {
		if !item.HasParent {
			if _, ok := tree.Item[item.ID]; !ok {
				treeItem, hasUpdated := sm.assembleItem(item.ID)
				if hasUpdated {
					tree.Item[item.ID] = treeItem
				}
			}
		}
	}
	for _, player := range sm.State.Player {
		if !player.HasParent {
			if _, ok := tree.Player[player.ID]; !ok {
				treePlayer, hasUpdated := sm.assemblePlayer(player.ID)
				if hasUpdated {
					tree.Player[player.ID] = treePlayer
				}
			}
		}
	}
	for _, position := range sm.State.Position {
		if !position.HasParent {
			if _, ok := tree.Position[position.ID]; !ok {
				treePosition, hasUpdated := sm.assemblePosition(position.ID)
				if hasUpdated {
					tree.Position[position.ID] = treePosition
				}
			}
		}
	}
	for _, zone := range sm.State.Zone {
		if _, ok := tree.Zone[zone.ID]; !ok {
			treeZone, hasUpdated := sm.assembleZone(zone.ID)
			if hasUpdated {
				tree.Zone[zone.ID] = treeZone
			}
		}
	}
	for _, zoneItem := range sm.State.ZoneItem {
		if !zoneItem.HasParent {
			if _, ok := tree.ZoneItem[zoneItem.ID]; !ok {
				treeZoneItem, hasUpdated := sm.assembleZoneItem(zoneItem.ID)
				if hasUpdated {
					tree.ZoneItem[zoneItem.ID] = treeZoneItem
				}
			}
		}
	}
	return tree
}`

const CreateGearScore_StateMachine_func string = `func (sm *StateMachine) CreateGearScore() GearScore {
	return sm.createGearScore(false)
}`

const createGearScore_StateMachine_func string = `func (sm *StateMachine) createGearScore(hasParent bool) GearScore {
	var e gearScoreCore
	e.ID = GearScoreID(sm.GenerateID())
	e.HasParent = hasParent
	e.OperationKind = OperationKindUpdate
	sm.Patch.GearScore[e.ID] = e
	return GearScore{gearScore: e}
}`

const CreatePosition_StateMachine_func string = `func (sm *StateMachine) CreatePosition() Position {
	return sm.createPosition(false)
}`

const createPosition_StateMachine_func string = `func (sm *StateMachine) createPosition(hasParent bool) Position {
	var e positionCore
	e.ID = PositionID(sm.GenerateID())
	e.HasParent = hasParent
	e.OperationKind = OperationKindUpdate
	sm.Patch.Position[e.ID] = e
	return Position{position: e}
}`

const CreateItem_StateMachine_func string = `func (sm *StateMachine) CreateItem() Item {
	return sm.createItem(false)
}`

const createItem_StateMachine_func string = `func (sm *StateMachine) createItem(hasParent bool) Item {
	var e itemCore
	e.ID = ItemID(sm.GenerateID())
	e.HasParent = hasParent
	elementGearScore := sm.createGearScore(true)
	e.GearScore = elementGearScore.gearScore.ID
	e.OperationKind = OperationKindUpdate
	sm.Patch.Item[e.ID] = e
	return Item{item: e}
}`

const CreateZoneItem_StateMachine_func string = `func (sm *StateMachine) CreateZoneItem() ZoneItem {
	return sm.createZoneItem(false)
}`

const createZoneItem_StateMachine_func string = `func (sm *StateMachine) createZoneItem(hasParent bool) ZoneItem {
	var e zoneItemCore
	e.ID = ZoneItemID(sm.GenerateID())
	e.HasParent = hasParent
	elementItem := sm.createItem(true)
	e.Item = elementItem.item.ID
	elementPosition := sm.createPosition(true)
	e.Position = elementPosition.position.ID
	e.OperationKind = OperationKindUpdate
	sm.Patch.ZoneItem[e.ID] = e
	return ZoneItem{zoneItem: e}
}`

const CreatePlayer_StateMachine_func string = `func (sm *StateMachine) CreatePlayer() Player {
	return sm.createPlayer(false)
}`

const createPlayer_StateMachine_func string = `func (sm *StateMachine) createPlayer(hasParent bool) Player {
	var e playerCore
	e.ID = PlayerID(sm.GenerateID())
	e.HasParent = hasParent
	elementGearScore := sm.createGearScore(true)
	e.GearScore = elementGearScore.gearScore.ID
	elementPosition := sm.createPosition(true)
	e.Position = elementPosition.position.ID
	e.OperationKind = OperationKindUpdate
	sm.Patch.Player[e.ID] = e
	return Player{player: e}
}`

const CreateZone_StateMachine_func string = `func (sm *StateMachine) CreateZone() Zone {
	return sm.createZone()
}`

const createZone_StateMachine_func string = `func (sm *StateMachine) createZone() Zone {
	var e zoneCore
	e.ID = ZoneID(sm.GenerateID())
	e.OperationKind = OperationKindUpdate
	sm.Patch.Zone[e.ID] = e
	return Zone{zone: e}
}`

const DeletePlayer_StateMachine_func string = `func (sm *StateMachine) DeletePlayer(playerID PlayerID) {
	player := sm.GetPlayer(playerID).player
	if player.HasParent {
		return
	}
	player.OperationKind = OperationKindDelete
	sm.Patch.Player[player.ID] = player
	sm.DeleteGearScore(player.GearScore)
	for _, itemID := range player.Items {
		sm.DeleteItem(itemID)
	}
	sm.DeletePosition(player.Position)
}`

const DeleteGearScore_StateMachine_func string = `func (sm *StateMachine) DeleteGearScore(gearScoreID GearScoreID) {
	gearScore := sm.GetGearScore(gearScoreID).gearScore
	if gearScore.HasParent {
		return
	}
	gearScore.OperationKind = OperationKindDelete
	sm.Patch.GearScore[gearScore.ID] = gearScore
}`

const DeletePosition_StateMachine_func string = `func (sm *StateMachine) DeletePosition(positionID PositionID) {
	position := sm.GetPosition(positionID).position
	if position.HasParent {
		return
	}
	position.OperationKind = OperationKindDelete
	sm.Patch.Position[position.ID] = position
}`

const DeleteItem_StateMachine_func string = `func (sm *StateMachine) DeleteItem(itemID ItemID) {
	item := sm.GetItem(itemID).item
	if item.HasParent {
		return
	}
	item.OperationKind = OperationKindDelete
	sm.Patch.Item[item.ID] = item
	sm.DeleteGearScore(item.GearScore)
}`

const DeleteZoneItem_StateMachine_func string = `func (sm *StateMachine) DeleteZoneItem(zoneItemID ZoneItemID) {
	zoneItem := sm.GetZoneItem(zoneItemID).zoneItem
	if zoneItem.HasParent {
		return
	}
	zoneItem.OperationKind = OperationKindDelete
	sm.Patch.ZoneItem[zoneItem.ID] = zoneItem
	sm.DeleteItem(zoneItem.Item)
	sm.DeletePosition(zoneItem.Position)
}`

const DeleteZone_StateMachine_func string = `func (sm *StateMachine) DeleteZone(zoneID ZoneID) {
	zone := sm.GetZone(zoneID).zone
	zone.OperationKind = OperationKindDelete
	sm.Patch.Zone[zone.ID] = zone
	for _, zoneItemID := range zone.Items {
		sm.DeleteZoneItem(zoneItemID)
	}
	for _, playerID := range zone.Players {
		sm.DeletePlayer(playerID)
	}
}`

const GetPlayer_StateMachine_func string = `func (sm *StateMachine) GetPlayer(playerID PlayerID) Player {
	patchingPlayer, ok := sm.Patch.Player[playerID]
	if ok {
		return Player{patchingPlayer}
	}
	currentPlayer := sm.State.Player[playerID]
	return Player{currentPlayer}
}`

const GetItems_Player_func string = `func (_e Player) GetItems(sm *StateMachine) []Item {
	e := sm.GetPlayer(_e.player.ID)
	var items []Item
	for _, itemID := range e.player.Items {
		items = append(items, sm.GetItem(itemID))
	}
	return items
}`

const GetGearScore_Player_func string = `func (_e Player) GetGearScore(sm *StateMachine) GearScore {
	e := sm.GetPlayer(_e.player.ID)
	return sm.GetGearScore(e.player.GearScore)
}`

const GetPosition_Player_func string = `func (_e Player) GetPosition(sm *StateMachine) Position {
	e := sm.GetPlayer(_e.player.ID)
	return sm.GetPosition(e.player.Position)
}`

const GetGearScore_StateMachine_func string = `func (sm *StateMachine) GetGearScore(gearScoreID GearScoreID) GearScore {
	patchingGearScore, ok := sm.Patch.GearScore[gearScoreID]
	if ok {
		return GearScore{patchingGearScore}
	}
	currentGearScore := sm.State.GearScore[gearScoreID]
	return GearScore{currentGearScore}
}`

const GetLevel_GearScore_func string = `func (_e GearScore) GetLevel(sm *StateMachine) int {
	e := sm.GetGearScore(_e.gearScore.ID)
	return e.gearScore.Level
}`

const GetScore_GearScore_func string = `func (_e GearScore) GetScore(sm *StateMachine) int {
	e := sm.GetGearScore(_e.gearScore.ID)
	return e.gearScore.Score
}`

const GetItem_StateMachine_func string = `func (sm *StateMachine) GetItem(itemID ItemID) Item {
	patchingItem, ok := sm.Patch.Item[itemID]
	if ok {
		return Item{patchingItem}
	}
	currentItem := sm.State.Item[itemID]
	return Item{currentItem}
}`

const GetGearScore_Item_func string = `func (_e Item) GetGearScore(sm *StateMachine) GearScore {
	e := sm.GetItem(_e.item.ID)
	return sm.GetGearScore(e.item.GearScore)
}`

const GetPosition_StateMachine_func string = `func (sm *StateMachine) GetPosition(positionID PositionID) Position {
	patchingPosition, ok := sm.Patch.Position[positionID]
	if ok {
		return Position{patchingPosition}
	}
	currentPosition := sm.State.Position[positionID]
	return Position{currentPosition}
}`

const GetX_Position_func string = `func (_e Position) GetX(sm *StateMachine) float64 {
	e := sm.GetPosition(_e.position.ID)
	return e.position.X
}`

const GetY_Position_func string = `func (_e Position) GetY(sm *StateMachine) float64 {
	e := sm.GetPosition(_e.position.ID)
	return e.position.Y
}`

const GetZoneItem_StateMachine_func string = `func (sm *StateMachine) GetZoneItem(zoneItemID ZoneItemID) ZoneItem {
	patchingZoneItem, ok := sm.Patch.ZoneItem[zoneItemID]
	if ok {
		return ZoneItem{patchingZoneItem}
	}
	currentZoneItem := sm.State.ZoneItem[zoneItemID]
	return ZoneItem{currentZoneItem}
}`

const GetPosition_ZoneItem_func string = `func (_e ZoneItem) GetPosition(sm *StateMachine) Position {
	e := sm.GetZoneItem(_e.zoneItem.ID)
	return sm.GetPosition(e.zoneItem.Position)
}`

const GetItem_ZoneItem_func string = `func (_e ZoneItem) GetItem(sm *StateMachine) Item {
	e := sm.GetZoneItem(_e.zoneItem.ID)
	return sm.GetItem(e.zoneItem.Item)
}`

const GetZone_StateMachine_func string = `func (sm *StateMachine) GetZone(zoneID ZoneID) Zone {
	patchingZone, ok := sm.Patch.Zone[zoneID]
	if ok {
		return Zone{patchingZone}
	}
	currentZone := sm.State.Zone[zoneID]
	return Zone{currentZone}
}`

const GetPlayers_Zone_func string = `func (_e Zone) GetPlayers(sm *StateMachine) []Player {
	e := sm.GetZone(_e.zone.ID)
	var players []Player
	for _, playerID := range e.zone.Players {
		players = append(players, sm.GetPlayer(playerID))
	}
	return players
}`

const GetItems_Zone_func string = `func (_e Zone) GetItems(sm *StateMachine) []ZoneItem {
	e := sm.GetZone(_e.zone.ID)
	var items []ZoneItem
	for _, zoneItemID := range e.zone.Items {
		items = append(items, sm.GetZoneItem(zoneItemID))
	}
	return items
}`

const GetTags_Zone_func string = `func (_e Zone) GetTags(sm *StateMachine) []string {
	e := sm.GetZone(_e.zone.ID)
	var tags []string
	for _, element := range e.zone.Tags {
		tags = append(tags, element)
	}
	return tags
}`

const deduplicateGearScoreIDs_func string = `func deduplicateGearScoreIDs(a []GearScoreID, b []GearScoreID) []GearScoreID {
	check := make(map[GearScoreID]bool)
	deduped := make([]GearScoreID, 0)
	for _, val := range a {
		check[val] = true
	}
	for _, val := range b {
		check[val] = true
	}
	for letter := range check {
		deduped = append(deduped, letter)
	}
	return deduped
}`

const deduplicateItemIDs_func string = `func deduplicateItemIDs(a []ItemID, b []ItemID) []ItemID {
	check := make(map[ItemID]bool)
	deduped := make([]ItemID, 0)
	for _, val := range a {
		check[val] = true
	}
	for _, val := range b {
		check[val] = true
	}
	for letter := range check {
		deduped = append(deduped, letter)
	}
	return deduped
}`

const deduplicatePlayerIDs_func string = `func deduplicatePlayerIDs(a []PlayerID, b []PlayerID) []PlayerID {
	check := make(map[PlayerID]bool)
	deduped := make([]PlayerID, 0)
	for _, val := range a {
		check[val] = true
	}
	for _, val := range b {
		check[val] = true
	}
	for letter := range check {
		deduped = append(deduped, letter)
	}
	return deduped
}`

const deduplicatePositionIDs_func string = `func deduplicatePositionIDs(a []PositionID, b []PositionID) []PositionID {
	check := make(map[PositionID]bool)
	deduped := make([]PositionID, 0)
	for _, val := range a {
		check[val] = true
	}
	for _, val := range b {
		check[val] = true
	}
	for letter := range check {
		deduped = append(deduped, letter)
	}
	return deduped
}`

const deduplicateZoneIDs_func string = `func deduplicateZoneIDs(a []ZoneID, b []ZoneID) []ZoneID {
	check := make(map[ZoneID]bool)
	deduped := make([]ZoneID, 0)
	for _, val := range a {
		check[val] = true
	}
	for _, val := range b {
		check[val] = true
	}
	for letter := range check {
		deduped = append(deduped, letter)
	}
	return deduped
}`

const deduplicateZoneItemIDs_func string = `func deduplicateZoneItemIDs(a []ZoneItemID, b []ZoneItemID) []ZoneItemID {
	check := make(map[ZoneItemID]bool)
	deduped := make([]ZoneItemID, 0)
	for _, val := range a {
		check[val] = true
	}
	for _, val := range b {
		check[val] = true
	}
	for letter := range check {
		deduped = append(deduped, letter)
	}
	return deduped
}`

const RemovePlayers_Zone_func string = `func (_e Zone) RemovePlayers(sm *StateMachine, playersToRemove ...PlayerID) Zone {
	e := sm.GetZone(_e.zone.ID)
	if e.zone.OperationKind == OperationKindDelete {
		return e
	}
	var elementsAltered bool
	var newElements []PlayerID
	for _, element := range e.zone.Players {
		var toBeRemoved bool
		for _, elementToRemove := range playersToRemove {
			if element == elementToRemove {
				toBeRemoved = true
				elementsAltered = true
				sm.DeletePlayer(element)
			}
		}
		if !toBeRemoved {
			newElements = append(newElements, element)
		}
	}
	if !elementsAltered {
		return e
	}
	e.zone.Players = newElements
	e.zone.OperationKind = OperationKindUpdate
	sm.Patch.Zone[e.zone.ID] = e.zone
	return e
}`

const RemoveZoneItems_Zone_func string = `func (_e Zone) RemoveZoneItems(sm *StateMachine, zoneItemsToRemove ...ZoneItemID) Zone {
	e := sm.GetZone(_e.zone.ID)
	if e.zone.OperationKind == OperationKindDelete {
		return e
	}
	var elementsAltered bool
	var newElements []ZoneItemID
	for _, element := range e.zone.Items {
		var toBeRemoved bool
		for _, elementToRemove := range zoneItemsToRemove {
			if element == elementToRemove {
				toBeRemoved = true
				elementsAltered = true
				sm.DeleteZoneItem(element)
			}
		}
		if !toBeRemoved {
			newElements = append(newElements, element)
		}
	}
	if !elementsAltered {
		return e
	}
	e.zone.Items = newElements
	e.zone.OperationKind = OperationKindUpdate
	sm.Patch.Zone[e.zone.ID] = e.zone
	return e
}`

const RemoveItems_Player_func string = `func (_e Player) RemoveItems(sm *StateMachine, itemsToRemove ...ItemID) Player {
	e := sm.GetPlayer(_e.player.ID)
	if e.player.OperationKind == OperationKindDelete {
		return e
	}
	var elementsAltered bool
	var newElements []ItemID
	for _, element := range e.player.Items {
		var toBeRemoved bool
		for _, elementToRemove := range itemsToRemove {
			if element == elementToRemove {
				toBeRemoved = true
				elementsAltered = true
				sm.DeleteItem(element)
			}
		}
		if !toBeRemoved {
			newElements = append(newElements, element)
		}
	}
	if !elementsAltered {
		return e
	}
	e.player.Items = newElements
	e.player.OperationKind = OperationKindUpdate
	sm.Patch.Player[e.player.ID] = e.player
	return e
}`

const RemoveTags_Zone_func string = `func (_e Zone) RemoveTags(sm *StateMachine, tagsToRemove ...string) Zone {
	e := sm.GetZone(_e.zone.ID)
	if e.zone.OperationKind == OperationKindDelete {
		return e
	}
	var elementsAltered bool
	var newElements []string
	for _, element := range e.zone.Tags {
		var toBeRemoved bool
		for _, elementToRemove := range tagsToRemove {
			if element == elementToRemove {
				toBeRemoved = true
				elementsAltered = true
			}
		}
		if !toBeRemoved {
			newElements = append(newElements, element)
		}
	}
	if !elementsAltered {
		return e
	}
	e.zone.Tags = newElements
	e.zone.OperationKind = OperationKindUpdate
	sm.Patch.Zone[e.zone.ID] = e.zone
	return e
}`

const SetLevel_GearScore_func string = `func (_e GearScore) SetLevel(sm *StateMachine, newLevel int) GearScore {
	e := sm.GetGearScore(_e.gearScore.ID)
	if e.gearScore.OperationKind == OperationKindDelete {
		return e
	}
	e.gearScore.Level = newLevel
	e.gearScore.OperationKind = OperationKindUpdate
	sm.Patch.GearScore[e.gearScore.ID] = e.gearScore
	return e
}`

const SetScore_GearScore_func string = `func (_e GearScore) SetScore(sm *StateMachine, newScore int) GearScore {
	e := sm.GetGearScore(_e.gearScore.ID)
	if e.gearScore.OperationKind == OperationKindDelete {
		return e
	}
	e.gearScore.Score = newScore
	e.gearScore.OperationKind = OperationKindUpdate
	sm.Patch.GearScore[e.gearScore.ID] = e.gearScore
	return e
}`

const SetX_Position_func string = `func (_e Position) SetX(sm *StateMachine, newX float64) Position {
	e := sm.GetPosition(_e.position.ID)
	if e.position.OperationKind == OperationKindDelete {
		return e
	}
	e.position.X = newX
	e.position.OperationKind = OperationKindUpdate
	sm.Patch.Position[e.position.ID] = e.position
	return e
}`

const SetY_Position_func string = `func (_e Position) SetY(sm *StateMachine, newY float64) Position {
	e := sm.GetPosition(_e.position.ID)
	if e.position.OperationKind == OperationKindDelete {
		return e
	}
	e.position.Y = newY
	e.position.OperationKind = OperationKindUpdate
	sm.Patch.Position[e.position.ID] = e.position
	return e
}`

const EntityKind_type string = `type EntityKind string`

const EntityKindGearScore_type string = `const (
	EntityKindGearScore	EntityKind	= "gearScore"
	EntityKindItem				= "item"
	EntityKindPlayer			= "player"
	EntityKindPosition			= "position"
	EntityKindZone				= "zone"
	EntityKindZoneItem			= "zoneItem"
)`

const GearScoreID_type string = `type GearScoreID int`

const ItemID_type string = `type ItemID int`

const PlayerID_type string = `type PlayerID int`

const PositionID_type string = `type PositionID int`

const ZoneID_type string = `type ZoneID int`

const ZoneItemID_type string = `type ZoneItemID int`

const State_type string = `type State struct {
	GearScore	map[GearScoreID]gearScoreCore	` + "`" + `json:"gearScore"` + "`" + `
	Item		map[ItemID]itemCore		` + "`" + `json:"item"` + "`" + `
	Player		map[PlayerID]playerCore		` + "`" + `json:"player"` + "`" + `
	Position	map[PositionID]positionCore	` + "`" + `json:"position"` + "`" + `
	Zone		map[ZoneID]zoneCore		` + "`" + `json:"zone"` + "`" + `
	ZoneItem	map[ZoneItemID]zoneItemCore	` + "`" + `json:"zoneItem"` + "`" + `
}`

const newState_func string = `func newState() State {
	return State{GearScore: make(map[GearScoreID]gearScoreCore), Item: make(map[ItemID]itemCore), Player: make(map[PlayerID]playerCore), Position: make(map[PositionID]positionCore), Zone: make(map[ZoneID]zoneCore), ZoneItem: make(map[ZoneItemID]zoneItemCore)}
}`

const zoneCore_type string = `type zoneCore struct {
	ID		ZoneID		` + "`" + `json:"id"` + "`" + `
	Items		[]ZoneItemID	` + "`" + `json:"items"` + "`" + `
	Players		[]PlayerID	` + "`" + `json:"players"` + "`" + `
	Tags		[]string	` + "`" + `json:"tags"` + "`" + `
	OperationKind	OperationKind	` + "`" + `json:"operationKind"` + "`" + `
}`

const Zone_type string = `type Zone struct{ zone zoneCore }`

const zoneItemCore_type string = `type zoneItemCore struct {
	ID		ZoneItemID	` + "`" + `json:"id"` + "`" + `
	Item		ItemID		` + "`" + `json:"item"` + "`" + `
	Position	PositionID	` + "`" + `json:"position"` + "`" + `
	OperationKind	OperationKind	` + "`" + `json:"operationKind"` + "`" + `
	HasParent	bool		` + "`" + `json:"hasParent"` + "`" + `
}`

const ZoneItem_type string = `type ZoneItem struct{ zoneItem zoneItemCore }`

const itemCore_type string = `type itemCore struct {
	ID		ItemID		` + "`" + `json:"id"` + "`" + `
	GearScore	GearScoreID	` + "`" + `json:"gearScore"` + "`" + `
	OperationKind	OperationKind	` + "`" + `json:"operationKind"` + "`" + `
	HasParent	bool		` + "`" + `json:"hasParent"` + "`" + `
}`

const Item_type string = `type Item struct{ item itemCore }`

const playerCore_type string = `type playerCore struct {
	ID		PlayerID	` + "`" + `json:"id"` + "`" + `
	GearScore	GearScoreID	` + "`" + `json:"gearScore"` + "`" + `
	Items		[]ItemID	` + "`" + `json:"items"` + "`" + `
	Position	PositionID	` + "`" + `json:"position"` + "`" + `
	OperationKind	OperationKind	` + "`" + `json:"operationKind"` + "`" + `
	HasParent	bool		` + "`" + `json:"hasParent"` + "`" + `
}`

const Player_type string = `type Player struct{ player playerCore }`

const gearScoreCore_type string = `type gearScoreCore struct {
	ID		GearScoreID	` + "`" + `json:"id"` + "`" + `
	Level		int		` + "`" + `json:"level"` + "`" + `
	Score		int		` + "`" + `json:"score"` + "`" + `
	OperationKind	OperationKind	` + "`" + `json:"operationKind"` + "`" + `
	HasParent	bool		` + "`" + `json:"hasParent"` + "`" + `
}`

const GearScore_type string = `type GearScore struct{ gearScore gearScoreCore }`

const positionCore_type string = `type positionCore struct {
	ID		PositionID	` + "`" + `json:"id"` + "`" + `
	X		float64		` + "`" + `json:"x"` + "`" + `
	Y		float64		` + "`" + `json:"y"` + "`" + `
	OperationKind	OperationKind	` + "`" + `json:"operationKind"` + "`" + `
	HasParent	bool		` + "`" + `json:"hasParent"` + "`" + `
}`

const Position_type string = `type Position struct{ position positionCore }`

const OperationKind_type string = `type OperationKind string`

const OperationKindDelete_type string = `const (
	OperationKindDelete	= "DELETE"
	OperationKindUpdate	= "UPDATE"
)`

const StateMachine_type string = `type StateMachine struct {
	State	State
	Patch	State
	IDgen	int
}`

const newStateMachine_func string = `func newStateMachine() *StateMachine {
	return &StateMachine{State: newState(), Patch: newState(), IDgen: 1}
}`

const GenerateID_StateMachine_func string = `func (sm *StateMachine) GenerateID() int {
	newID := sm.IDgen
	sm.IDgen = sm.IDgen + 1
	return newID
}`

const UpdateState_StateMachine_func string = `func (sm *StateMachine) UpdateState() {
	for _, gearScore := range sm.Patch.GearScore {
		if gearScore.OperationKind == OperationKindDelete {
			delete(sm.State.GearScore, gearScore.ID)
		} else {
			sm.State.GearScore[gearScore.ID] = gearScore
		}
	}
	for _, item := range sm.Patch.Item {
		if item.OperationKind == OperationKindDelete {
			delete(sm.State.Item, item.ID)
		} else {
			sm.State.Item[item.ID] = item
		}
	}
	for _, player := range sm.Patch.Player {
		if player.OperationKind == OperationKindDelete {
			delete(sm.State.Player, player.ID)
		} else {
			sm.State.Player[player.ID] = player
		}
	}
	for _, position := range sm.Patch.Position {
		if position.OperationKind == OperationKindDelete {
			delete(sm.State.Position, position.ID)
		} else {
			sm.State.Position[position.ID] = position
		}
	}
	for _, zone := range sm.Patch.Zone {
		if zone.OperationKind == OperationKindDelete {
			delete(sm.State.Zone, zone.ID)
		} else {
			sm.State.Zone[zone.ID] = zone
		}
	}
	for _, zoneItem := range sm.Patch.ZoneItem {
		if zoneItem.OperationKind == OperationKindDelete {
			delete(sm.State.ZoneItem, zoneItem.ID)
		} else {
			sm.State.ZoneItem[zoneItem.ID] = zoneItem
		}
	}
	sm.Patch = newState()
}`

const Tree_type string = `type Tree struct {
	GearScore	map[GearScoreID]_gearScore	` + "`" + `json:"gearScore"` + "`" + `
	Item		map[ItemID]_item		` + "`" + `json:"item"` + "`" + `
	Player		map[PlayerID]_player		` + "`" + `json:"player"` + "`" + `
	Position	map[PositionID]_position	` + "`" + `json:"position"` + "`" + `
	Zone		map[ZoneID]_zone		` + "`" + `json:"zone"` + "`" + `
	ZoneItem	map[ZoneItemID]_zoneItem	` + "`" + `json:"zoneItem"` + "`" + `
}`

const newTree_func string = `func newTree() Tree {
	return Tree{GearScore: make(map[GearScoreID]_gearScore), Item: make(map[ItemID]_item), Player: make(map[PlayerID]_player), Position: make(map[PositionID]_position), Zone: make(map[ZoneID]_zone), ZoneItem: make(map[ZoneItemID]_zoneItem)}
}`

const _zoneItem_type string = `type _zoneItem struct {
	ID		ZoneItemID	` + "`" + `json:"id"` + "`" + `
	Item		*_item		` + "`" + `json:"item"` + "`" + `
	Position	*_position	` + "`" + `json:"position"` + "`" + `
	OperationKind	OperationKind	` + "`" + `json:"operationKind"` + "`" + `
}`

const _item_type string = `type _item struct {
	ID		ItemID		` + "`" + `json:"id"` + "`" + `
	GearScore	*_gearScore	` + "`" + `json:"gearScore"` + "`" + `
	OperationKind	OperationKind	` + "`" + `json:"operationKind"` + "`" + `
}`

const _position_type string = `type _position struct {
	ID		PositionID	` + "`" + `json:"id"` + "`" + `
	X		float64		` + "`" + `json:"x"` + "`" + `
	Y		float64		` + "`" + `json:"y"` + "`" + `
	OperationKind	OperationKind	` + "`" + `json:"operationKind"` + "`" + `
}`

const _gearScore_type string = `type _gearScore struct {
	ID		GearScoreID	` + "`" + `json:"id"` + "`" + `
	Level		int		` + "`" + `json:"level"` + "`" + `
	Score		int		` + "`" + `json:"score"` + "`" + `
	OperationKind	OperationKind	` + "`" + `json:"operationKind"` + "`" + `
}`

const _player_type string = `type _player struct {
	ID		PlayerID	` + "`" + `json:"id"` + "`" + `
	GearScore	*_gearScore	` + "`" + `json:"gearScore"` + "`" + `
	Items		[]_item		` + "`" + `json:"items"` + "`" + `
	Position	*_position	` + "`" + `json:"position"` + "`" + `
	OperationKind	OperationKind	` + "`" + `json:"operationKind"` + "`" + `
}`

const _zone_type string = `type _zone struct {
	ID		ZoneID		` + "`" + `json:"id"` + "`" + `
	Items		[]_zoneItem	` + "`" + `json:"items"` + "`" + `
	Players		[]_player	` + "`" + `json:"players"` + "`" + `
	Tags		[]string	` + "`" + `json:"tags"` + "`" + `
	OperationKind	OperationKind	` + "`" + `json:"operationKind"` + "`" + `
}`
