// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  server

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Client ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Client ) UnmarshalJSON([]byte) error { return nil }
func ( Client ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Client ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Client *Client

func ( Lobby ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Lobby ) UnmarshalJSON([]byte) error { return nil }
func ( Lobby ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Lobby ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Lobby *Lobby

func ( Message ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Message ) UnmarshalJSON([]byte) error { return nil }
func ( Message ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Message ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Message *Message

func ( Room ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Room ) UnmarshalJSON([]byte) error { return nil }
func ( Room ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Room ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Room *Room

func ( Server ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Server ) UnmarshalJSON([]byte) error { return nil }
func ( Server ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Server ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Server *Server

func ( clientRegistrar ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* clientRegistrar ) UnmarshalJSON([]byte) error { return nil }
func ( clientRegistrar ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* clientRegistrar ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_clientRegistrar *clientRegistrar
