// this file was generated by https://github.com/Java-Jonas/decltostring

package serverfactory

const gets_generated_go_import string = `import (
	"errors"
	"log"
	"net/http"
)`

const messageKindAction_addItemToPlayer_type string = `const (
	messageKindAction_addItemToPlayer	messageKind	= 1
	messageKindAction_movePlayer		messageKind	= 2
	messageKindAction_spawnZoneItems	messageKind	= 3
)`

const _MovePlayerParams_type string = `type MovePlayerParams struct {
	ChangeX		float64		` + "`" + `json:"changeX"` + "`" + `
	ChangeY		float64		` + "`" + `json:"changeY"` + "`" + `
	PlayerID	PlayerID	` + "`" + `json:"playerID"` + "`" + `
}`

const _AddItemToPlayerParams_type string = `type AddItemToPlayerParams struct {
	Item		Item		` + "`" + `json:"item"` + "`" + `
	PlayerID	PlayerID	` + "`" + `json:"playerID"` + "`" + `
}`

const _SpawnZoneItemsParams_type string = `type SpawnZoneItemsParams struct {
	Items []Item ` + "`" + `json:"items"` + "`" + `
}`

const actions_type string = `type actions struct {
	addItemToPlayer	func(AddItemToPlayerParams, *Engine)
	movePlayer	func(MovePlayerParams, *Engine)
	spawnZoneItems	func(SpawnZoneItemsParams, *Engine)
}`

const processClientMessage_Room_func string = `func (r *Room) processClientMessage(msg message) error {
	switch messageKind(msg.Kind) {
	case messageKindAction_addItemToPlayer:
		var params AddItemToPlayerParams
		err := params.UnmarshalJSON(msg.Content)
		if err != nil {
			return err
		}
		r.actions.addItemToPlayer(params, r.state)
	case messageKindAction_movePlayer:
		var params MovePlayerParams
		err := params.UnmarshalJSON(msg.Content)
		if err != nil {
			return err
		}
		r.actions.movePlayer(params, r.state)
	case messageKindAction_spawnZoneItems:
		var params SpawnZoneItemsParams
		err := params.UnmarshalJSON(msg.Content)
		if err != nil {
			return err
		}
		r.actions.spawnZoneItems(params, r.state)
	default:
		return errors.New("unknown message kind")
	}
	return nil
}`

const _Start_func string = `func Start(movePlayer func(MovePlayerParams, *Engine), addItemToPlayer func(AddItemToPlayerParams, *Engine), spawnZoneItemsParams func(SpawnZoneItemsParams, *Engine), onDeploy func(*Engine), onFrameTick func(*Engine)) {
	log.Println("Hello World")
	a := actions{movePlayer, addItemToPlayer, spawnZoneItemsParams}
	setupRoutes(a, onDeploy, onFrameTick)
	log.Fatal(http.ListenAndServe(":8080", nil))
}`
