// this file was generated by https://github.com/Java-Jonas/decltostring

package serverfactory

const gets_generated_go_import string = `import (
	"fmt"
)`

const _MessageKindAction_addItemToPlayer_type string = `const (
	MessageKindAction_addItemToPlayer	MessageKind	= "addItemToPlayer"
	MessageKindAction_movePlayer		MessageKind	= "movePlayer"
	MessageKindAction_spawnZoneItems	MessageKind	= "spawnZoneItems"
)`

const _MovePlayerParams_type string = `type MovePlayerParams struct {
	ChangeX	float64		` + "`" + `json:"changeX"` + "`" + `
	ChangeY	float64		` + "`" + `json:"changeY"` + "`" + `
	Player	PlayerID	` + "`" + `json:"player"` + "`" + `
}`

const _AddItemToPlayerParams_type string = `type AddItemToPlayerParams struct {
	Item	ItemID	` + "`" + `json:"item"` + "`" + `
	NewName	string	` + "`" + `json:"newName"` + "`" + `
}`

const _SpawnZoneItemsParams_type string = `type SpawnZoneItemsParams struct {
	Items []ItemID ` + "`" + `json:"items"` + "`" + `
}`

const _AddItemToPlayerResponse_type string = `type AddItemToPlayerResponse struct {
	PlayerPath string ` + "`" + `json:"playerPath"` + "`" + `
}`

const _SpawnZoneItemsResponse_type string = `type SpawnZoneItemsResponse struct {
	NewZoneItemPaths []string ` + "`" + `json:"newZoneItemPaths"` + "`" + `
}`

const _Actions_type string = `type Actions struct {
	AddItemToPlayer	func(AddItemToPlayerParams, *Engine) AddItemToPlayerResponse
	MovePlayer	func(MovePlayerParams, *Engine)
	SpawnZoneItems	func(SpawnZoneItemsParams, *Engine) SpawnZoneItemsResponse
}`

const _SideEffects_type string = `type SideEffects struct {
	OnDeploy	func(*Engine)
	OnFrameTick	func(*Engine)
}`

const processClientMessage_Room_func string = `func (r *Room) processClientMessage(msg Message) (Message, error) {
	switch MessageKind(msg.Kind) {
	case MessageKindAction_addItemToPlayer:
		if r.actions.AddItemToPlayer == nil {
			break
		}
		var params AddItemToPlayerParams
		err := params.UnmarshalJSON(msg.Content)
		if err != nil {
			return Message{MessageKindError, messageUnmarshallingError(msg.Content, err), msg.client}, err
		}
		res := r.actions.AddItemToPlayer(params, r.state)
		resContent, err := res.MarshalJSON()
		if err != nil {
			return Message{MessageKindError, responseMarshallingError(msg.Content, err), msg.client}, err
		}
		return Message{msg.Kind, resContent, msg.client}, nil
	case MessageKindAction_movePlayer:
		if r.actions.MovePlayer == nil {
			break
		}
		var params MovePlayerParams
		err := params.UnmarshalJSON(msg.Content)
		if err != nil {
			return Message{MessageKindError, messageUnmarshallingError(msg.Content, err), msg.client}, err
		}
		r.actions.MovePlayer(params, r.state)
		return Message{}, nil
	case MessageKindAction_spawnZoneItems:
		if r.actions.SpawnZoneItems == nil {
			break
		}
		var params SpawnZoneItemsParams
		err := params.UnmarshalJSON(msg.Content)
		if err != nil {
			return Message{MessageKindError, messageUnmarshallingError(msg.Content, err), msg.client}, err
		}
		res := r.actions.SpawnZoneItems(params, r.state)
		resContent, err := res.MarshalJSON()
		if err != nil {
			return Message{MessageKindError, responseMarshallingError(msg.Content, err), msg.client}, err
		}
		return Message{msg.Kind, resContent, msg.client}, nil
	default:
		return Message{MessageKindError, []byte("unknown message kind " + msg.Kind), msg.client}, fmt.Errorf("unknown message kind in: %s", printMessage(msg))
	}
	return Message{}, nil
}`
