// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  state

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Client ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Client ) UnmarshalJSON([]byte) error { return nil }
func ( Client ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Client ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Client *Client
