// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  state

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Actions ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* Actions ) UnmarshalJSON([]byte) error { return nil }
func ( Actions ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Actions ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Actions *Actions

func ( AddItemToPlayerAction ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AddItemToPlayerAction ) UnmarshalJSON([]byte) error { return nil }
func ( AddItemToPlayerAction ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AddItemToPlayerAction ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AddItemToPlayerAction *AddItemToPlayerAction

func ( AddItemToPlayerParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AddItemToPlayerParams ) UnmarshalJSON([]byte) error { return nil }
func ( AddItemToPlayerParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AddItemToPlayerParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AddItemToPlayerParams *AddItemToPlayerParams

func ( AddItemToPlayerResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* AddItemToPlayerResponse ) UnmarshalJSON([]byte) error { return nil }
func ( AddItemToPlayerResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* AddItemToPlayerResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_AddItemToPlayerResponse *AddItemToPlayerResponse

func ( MovePlayerAction ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* MovePlayerAction ) UnmarshalJSON([]byte) error { return nil }
func ( MovePlayerAction ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* MovePlayerAction ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_MovePlayerAction *MovePlayerAction

func ( MovePlayerParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* MovePlayerParams ) UnmarshalJSON([]byte) error { return nil }
func ( MovePlayerParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* MovePlayerParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_MovePlayerParams *MovePlayerParams

func ( SpawnZoneItemsAction ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SpawnZoneItemsAction ) UnmarshalJSON([]byte) error { return nil }
func ( SpawnZoneItemsAction ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SpawnZoneItemsAction ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SpawnZoneItemsAction *SpawnZoneItemsAction

func ( SpawnZoneItemsParams ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SpawnZoneItemsParams ) UnmarshalJSON([]byte) error { return nil }
func ( SpawnZoneItemsParams ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SpawnZoneItemsParams ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SpawnZoneItemsParams *SpawnZoneItemsParams

func ( SpawnZoneItemsResponse ) MarshalJSON() ([]byte, error) { return nil, nil }
func (* SpawnZoneItemsResponse ) UnmarshalJSON([]byte) error { return nil }
func ( SpawnZoneItemsResponse ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* SpawnZoneItemsResponse ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SpawnZoneItemsResponse *SpawnZoneItemsResponse
