// this file was generated by https://github.com/Java-Jonas/decltostring

package package_name

const golden_book_go_import string = `import (
	"bytes"
	"fmt"
	"math/rand"
)`

const golden_book_type string = `type book struct {
	id	id
	name	string
	content	bytes.Buffer
}`

const golden_addContent_book_func string = `func (b *book) addContent(content []byte) {
	b.content.Write(content)
}`

const golden_newBook_func string = `func newBook(name string) book {
	return book{id: id(rand.Intn(100)), name: name, content: bytes.Buffer{}}
}`

const golden_print_book_func string = `func (b book) print() {
	fmt.Println(b.content.String())
}`

const golden_letter_go_import string = `import (
	"bytes"
	"fmt"
	"math/rand"
)`

const golden_letter_type string = `type letter struct {
	id	id
	content	bytes.Buffer
}`

const golden_newLetter_func string = `func newLetter(content []byte) letter {
	return letter{id: id(rand.Intn(100)), content: *bytes.NewBuffer(content)}
}`

const golden_print_letter_func string = `func (l letter) print() {
	fmt.Println(l.content.String())
}`

const golden_main_go_import string = `import "fmt"`

const golden_id_type string = `type id int`

const golden_defaultName_type string = `const (
	defaultName string = "Good Read"
)`

const golden_greeting_type string = `const greeting string = ` + "`" + `Dearest Person,
I'm sending you this letter to let you know` + "`" + ``

const golden_printable_type string = `type printable interface{ print() }`

const golden_main_func string = `func main() {
	myBook := newBook(defaultName)
	myBook.addContent([]byte(` + "`" + `This is a book about
one young fella who tried to change the world` + "`" + `))
	myBook.print()
	fmt.Println(myBook.name)
	myLetter := newLetter([]byte(greeting + ` + "`" + ` that at some point
I might be no more.` + "`" + `))
	myLetter.print()
}`
