// this file was generated by https://github.com/jobergner/decltostring
package message

const _MessageKindAction_addItemToPlayer_type string = `const (
	MessageKindAction_addItemToPlayer	Kind	= "addItemToPlayer"
	MessageKindAction_movePlayer		Kind	= "movePlayer"
	MessageKindAction_spawnZoneItems	Kind	= "spawnZoneItems"
)`
const parameter_generated_go_import string = `import (
	"github.com/jobergner/backent-cli/examples/state"
)`
const _MovePlayerParams_type string = `type MovePlayerParams struct {
	ChangeX	float64		` + "`" + `json:"changeX"` + "`" + `
	ChangeY	float64		` + "`" + `json:"changeY"` + "`" + `
	Player	state.PlayerID	` + "`" + `json:"player"` + "`" + `
}`
const _AddItemToPlayerParams_type string = `type AddItemToPlayerParams struct {
	Item	state.ItemID	` + "`" + `json:"item"` + "`" + `
	NewName	string		` + "`" + `json:"newName"` + "`" + `
}`
const _SpawnZoneItemsParams_type string = `type SpawnZoneItemsParams struct {
	Items []state.ItemID ` + "`" + `json:"items"` + "`" + `
}`
const _AddItemToPlayerResponse_type string = `type AddItemToPlayerResponse struct {
	PlayerPath string ` + "`" + `json:"playerPath"` + "`" + `
}`
const _SpawnZoneItemsResponse_type string = `type SpawnZoneItemsResponse struct {
	NewZoneItemPaths []string ` + "`" + `json:"newZoneItemPaths"` + "`" + `
}`

var decl_to_string_decl_collection = map[string]string{"_AddItemToPlayerParams_type": _AddItemToPlayerParams_type, "_AddItemToPlayerResponse_type": _AddItemToPlayerResponse_type, "_MessageKindAction_addItemToPlayer_type": _MessageKindAction_addItemToPlayer_type, "_MovePlayerParams_type": _MovePlayerParams_type, "_SpawnZoneItemsParams_type": _SpawnZoneItemsParams_type, "_SpawnZoneItemsResponse_type": _SpawnZoneItemsResponse_type}
